#!/usr/bin/env python3
import sys

if len (sys.argv) < 3:
    print ("usage: gen_c_embed output_file.c input0 [input1...]\n")
    exit (1);

output_file = sys.argv[1]
input_files = sys.argv[2:]

bad_opcode_str = ';BAD OP - '

with open (output_file, "w+", encoding="utf-8") as outfile:
    outfile.write (f"/* {output_file} - generated during build by gen_c_embeds\n")
    outfile.write (f" * from source files: {', '.join (input_files)}\n")
    outfile.write (f" * DO NOT EDIT, THIS FILE IS AUTOMATICALLY GENERATED */\n\n")

    outfile.write ("#include <stddef.h>\n\n")

    mnemonic_max_strlen = len(bad_opcode_str) + 2

    for input_file in input_files:
        with open (input_file, "r") as infile:
            input_contents = [l for l in infile.read ().split ('\n') if l != '']
            input_length = len (input_contents)

            var_name = input_file.replace ("i8080/", "") \
                                 .replace ("i8085/", "") \
                                 .replace ("z80intel/", "") \
                                 .replace ("z80/", "") \
                                 .replace ("./", "") \
                                 .replace (".txt", "") \
                                 .replace (".", "_") \
                                 .replace ("-", "_") \
                                 .upper ()

            outfile.write (f"const char *{var_name}_TABLE[256] = \u007b\n")

            opcode_index = -1;
            for line in input_contents:
                bytecode_str, mnemonic = line.split(' ', 1)
                bytecode = int('0x0' + bytecode_str, base = 16)

                for i in range(opcode_index+1, bytecode):
                    outfile.write (f"\t\"{bad_opcode_str}{i:02x}\",\n")

                outfile.write (f"\t\"{mnemonic}\",\n")
                opcode_index = bytecode


                mnemonic_strlen = len (mnemonic)
                if '@' in mnemonic:
                    mnemonic_strlen += 4
                elif '$' in mnemonic:
                    mnemonic_strlen += 2

                if mnemonic_strlen > mnemonic_max_strlen:
                    mnemonic_max_strlen = mnemonic_strlen

            for i in range(opcode_index+1, 0xff+1):
                outfile.write (f"\t\"{bad_opcode_str}{i:02x}\",\n")

            outfile.write (f"\u007d;\n\n")

    outfile.write (f"const size_t OPCODE_MAX_STRLEN = {mnemonic_max_strlen};\n\n")
    outfile.write ("/* end of file */")

# end of file
