#!/usr/bin/env bash

mnemonic=$1
map_file=$2
sed_file=$3

touch "$sed_file"
truncate -s 0 "$sed_file"
printf '#!/usr/bin/env sh\n' >>"$sed_file"
printf 'cat "$1" \\\n' >>"$sed_file"
while IFS= read -r line; do
    addr=`  echo "$line" |awk -F\  '{ print $1 }'`
    label=` echo "$line" |awk -F\  '{ print $2 }'`
    module=`echo "$line" |awk -F\  '{ print $3 }'`
    if [ "x$mnemonic" == 'xz80' ]; then
        printf "\t|sed 's/0x%s/%s%s/gi' \\\\\n" "$addr" "$module" "$label" >>"$sed_file"
    else # i8080
        printf "\t|sed 's/0%sh/%s%s/gi' \\\\\n" "$addr" "$module" "$label" >>"$sed_file"
    fi

done <<<`grep -E '^ +0000[A-F0-9]{4} +_[a-zA-Z0-9_]+ +[a-zA-Z0-9_]+$' $map_file \
        |sed 's/^ \+0000//'`
chmod +x "$sed_file"

# end of file
